### PR TITLE
Side menu in careers page close when the user clicks outside the menu

### PR DESCRIPTION
**Pull request by dangvu0502**
If the menu is open and the clicked target is not within the menu, menu will be closed.

This pull request is in regards to Issue #78

### CODE REVIEW

**Comment by Timonwa** [comment]
Hi @dangvu0502, thank you for this. There is a small problem though, you only did it for the frontend page, it doesn't work for the backend page. Can do it for that too? then I will be able to merge your pull request.

**Comment by dangvu0502** [comment]
I can do it for backend page too but how do i test it work for backend page.
This is my first time work with backend page :>

**Comment by Timonwa** [comment]
The backend career page is just like the frontend career page, You can click on the backend page card on the home page or careers page to navigate into the backend page and make the same updates you did to the frontend careers page.

**Comment by dangvu0502** [comment]
I got it

**Comment by Timonwa** [comment]
@all-contributors please add @dangvu0502 for code bug

**Pull request merged**
