### PR TITLE
Add Community section

### PR DESCRIPTION
**Pull request by siuting0511**
community section added with side-bar nav link.

### CODE REVIEW

**Comment by siuting0511** [comment]
Sure, I have just made the edit and committed to the pull request.

**Comment by Timonwa** [comment]
Thank you @siuting0511 . I will merge your pull request now.

**Comment by Timonwa** [comment]
@all-contributors please add @nigel0511 for code and resources

**Comment by Timonwa** [comment]
https://github.com/all-contributors please add @nigel0511 for code and resources

**Comment by Timonwa** [comment]
@all-contributors please add @nigel0511 for  content and code

**Pull request merged**
