### PR TITLE
Added two videos in the Career Page about what Frontend Development is.

### PR DESCRIPTION
**Pull request by codewithfan**

### CODE REVIEW

**Comment by Timonwa** [comment]
Hi @codewithfan the links you added are links to videos that talk about only frontend.
For the careers page we want videos that talk about the different career paths one can have in tech and not just frontend development.
If you click the links in the article section, you will see that they talked about different careers and how to pick one.

**Comment by codewithfan** [comment]
Hello @Timonwa. Thank you for the correction. Fixed the links.

**Comment by Timonwa** [comment]
Ok. These links are better now. I will merge this.

Also if you can find 1 to 2 videos that talk about no-code careers in tech, it would be much appreciated and useful too. You can create a new pull request on that cos this one will be closed.

**Comment by Timonwa** [comment]
@all-contributors please add @codewithfan for data

**Pull request merged**
