### PR TITLE
added the link for bitbucket resource by atlassian

### PR DESCRIPTION
**Pull request by anant-strong**
This was the video added: https://youtu.be/M44nEyd_5To
This is my second contribution to any project, so please give me your feedback on how I can bring perfection and get to work on the project.

### CODE REVIEW

**Comment by Timonwa** [comment]
Hi @anant-strong. I check the video you added, the comments on the video were not positive and it seemed the title of the video was misleading.

You can add this video instead: https://youtu.be/1tC6Z57AOkY.

Also you added the link to the side bar, instead of the [Bitbucket section ](https://careerroadmap.tech/html/careers/frontend.html#bitbucket) . And please follow the template when adding the link

**Comment by anant-strong** [comment]
Thanks, @Timonwa I am working on your suggestions.

**Comment by anant-strong** [comment]
Hey! @Timonwa I have made the changes as suggested by you can you please review it.

**Comment by Timonwa** [comment]
Looks good. I will merge it now.

**Pull request merged**
