### PR TITLE
Add Table of Content (Task 1)

### PR DESCRIPTION
**Pull request by anthonychinwe**
- I added links to the corresponding sections of the README.md file, based on their respective 'heading 2' anchor tags.

### CODE REVIEW

**Comment by Timonwa** [comment]
Welcome @anthonychinwe  and thank you for creating a Pull Request!
If your pull request gets merged, and you would like to be added to our MVPs list(contributors list) please reply to this comment with your details using the format below:

Name:
What you do:
Twitter handle:
Link (either to your website, blog, portfolio, GitHub, etc):

Do not forget to Star⭐ this repo if you have not.

Thank you.

**Comment by Timonwa** [comment]
Hi @anthonychinwe, Thank you for this, your pull request is going to be merged.

**Comment by anthonychinwe** [comment]
> Hi @anthonychinwe, Thank you for this, your pull request is going to be merged.

You're welcome @Timonwa

**Comment by Timonwa** [comment]
@all-contributors please add @anthonychinwe for documentation

**Pull request merged**
