### PR TITLE
Backend Language C

### PR DESCRIPTION
**Pull request by Goutham-erram**
I have added resources for backend language C. kindly validate and let me know if there are any issues.

### CODE REVIEW

**Comment by Timonwa** [comment]
@Goutham-erram I will check it out.

**Comment by Timonwa** [comment]
Thank you for this contribution @Goutham-erram. In the links for the articles, also add to it, the name of the website it was published at. 
Then delete the yarn.lock file before you push your changes again. Everything else looks good to me.

**Comment by Goutham-erram** [comment]
Yep, Will do that

**Comment by Goutham-erram** [comment]
I have updated the code and deleted the yarn.lock file. Kindly validate and let me know i there are any issues and i will proceed with other languages, next i will be doing C++

**Comment by Timonwa** [comment]
Everything looks good. You can start with the next one.  Thank you @Goutham-erram

**Pull request merged**
