### PR TITLE
added hover effect for link texts and divs

### PR DESCRIPTION
**Pull request by benjaminsanga**
Highlighting on hover of link texts and 'careers in tech' section. Also for the Table of content and footer links.

### CODE REVIEW

**Comment by Timonwa** [comment]
Thank you for this contribution @benjaminsanga. Can you also add the hover effect of the nav links to the logo for the navbar? Then also add a hover effect for the footer nav links and social media icons, since these already have a colour of white, you can use the body text colour for the hover effect. Then the links in the open-source section above the footer too can have a hover effect, you can use the purple colour for it. I think that would be all. Thank you.

**Comment by benjaminsanga** [comment]
Alright then, I will do that @Timonwa

**Comment by benjaminsanga** [comment]
Alright then, I will do that @Timonwa

**Comment by Timonwa** [comment]
Thank you @benjaminsanga. I will merge it now.

**Comment by Timonwa** [comment]
@all-contributors please add @benjaminsanga  for  design an code

**Pull request merged**
