### PR TITLE
Added more database languages

### PR DESCRIPTION
**Pull request by haseeb196**
Added more database languages #56. Please take a look at this PR.

### CODE REVIEW

**Comment by Timonwa** [comment]
Hi @haseeb196 . Thank you for the pull request.  I will review it soon.  In the mean time, please give us a star if you haven't already yet.  😊

**Comment by haseeb196** [comment]
> Hi @haseeb196 . Thank you for the pull request. I will review it soon. In the mean time, please give us a star if you haven't already yet. 😊



> Hi @haseeb196 . Thank you for the pull request. I will review it soon. In the mean time, please give us a star if you haven't already yet. 😊

okay 😊

**Comment by haseeb196** [comment]
> Hi @haseeb196 . Thank you for the pull request. I will review it soon. In the mean time, please give us a star if you haven't already yet. 😊

okay 😃

**Comment by Timonwa** [comment]
Hi @haseeb196 did you mean to close this pr?

**Comment by haseeb196** [comment]
> Hi @haseeb196 did you mean to close this pr?

no i didn't mean to close this, I was removing my old repo from GitHub and I accidently deleted this one also, so how can i reopen this again?

**Comment by Timonwa** [comment]
Since your repo was deleted, this PR cannot be opened again cos there is nothing to compare it to.

But since it's only one file you changed, you can easily fork the repo again and copy and paste your changes from here.

**Comment by Timonwa** [comment]
Since your repo was deleted, this PR cannot be opened again cos there is nothing to compare it to.

But since it's only one file you changed, you can easily fork the repo again and copy and paste your changes from here.

**Comment by haseeb196** [comment]
ok i will  do it

**Pull request closed without merging**
